package keys

// Actions of the shell. Views add their own.
const (
	QuitForce      Action = "quit.force"
	Quit           Action = "quit"
	OpenHelp       Action = "help"
	OpenAppearance Action = "appearance"
	Refresh        Action = "refresh"
	SwitchView     Action = "view.switch"
	Back           Action = "back"
	Close          Action = "close"
	OpenDetails    Action = "details"

	NavDown     Action = "nav.down"
	NavUp       Action = "nav.up"
	NavFirst    Action = "nav.first"
	NavLast     Action = "nav.last"
	NavHalfDown Action = "nav.halfdown"
	NavHalfUp   Action = "nav.halfup"
	NavPageDown Action = "nav.pagedown"
	NavPageUp   Action = "nav.pageup"
	Mark        Action = "mark"

	HelpFilter Action = "help.filter"

	Open         Action = "open"
	Left         Action = "left"
	Right        Action = "right"
	FoldAll      Action = "fold.all"
	UnfoldAll    Action = "unfold.all"
	FocusNext    Action = "focus.next"
	DetailToggle Action = "detail.toggle"
	SectionNext  Action = "section.next"
	SectionPrev  Action = "section.prev"
	Jump         Action = "jump"
	SectionsAll  Action = "sections.all"
	Markdown     Action = "markdown"

	ScrollLeft      Action = "scroll.left"
	ScrollRight     Action = "scroll.right"
	ScrollHalfLeft  Action = "scroll.halfleft"
	ScrollHalfRight Action = "scroll.halfright"
	DepthMore       Action = "depth.more"
	DepthLess       Action = "depth.less"
	ToggleIsolated  Action = "graph.isolated"

	Prev  Action = "prev"
	Next  Action = "next"
	Apply Action = "apply"

	OpenCommand Action = "bar.command"
	OpenSearch  Action = "bar.search"
	OpenFilter  Action = "bar.filter"
	OpenPicker  Action = "picker"

	BarAccept       Action = "bar.accept"
	BarUp           Action = "bar.up"
	BarDown         Action = "bar.down"
	BarIssueNext    Action = "bar.issue.next"
	BarIssuePrev    Action = "bar.issue.prev"
	BarComplete     Action = "bar.complete"
	BarCompleteBack Action = "bar.complete.back"
	BarToggle       Action = "bar.toggle"
	BarColumnNext   Action = "bar.column.next"
	BarColumnPrev   Action = "bar.column.prev"

	PickerMark   Action = "picker.mark"
	PickerClosed Action = "picker.closed"

	Retry  Action = "retry"
	Copy   Action = "copy"
	PickUp Action = "pick.up"
	PickDn Action = "pick.down"
)
